#Clean Dataset
Response.all.map { |c| c.destroy }
Outcome.all.map { |c| c.destroy }
Survey.all.map { |s| s.destroy }
Career.all.map { |c| c.destroy }
Choice.all.map { |c| c.destroy }
Question.all.map { |c| c.destroy }


#Create Questions   #using numbers as names of questions is provisory
Question.create(name: '1. ', description: 'Me trasladaria a una zona agricola - ganadera para ejercer mi profesion')
Question.create(name: '2. ', description: 'Tengo buena memoria y no me cuesta estudiar y retener formulas y palabras tecnicas.')
Question.create(name: '3. ', description: 'Me gusta escribir. En general mis trabajos son largos y estan bien organizados.')
Question.create(name: '4. ', description: 'Se quien es Steven Hawking: Conozco y me atraen sus descubrimientos.')
Question.create(name: '5. ', description: 'Me actualizo respecto de los avances tecnologicos y me intereso por investigar y conocer')
Question.create(name: '6. ', description: 'Se quien es Andy Warhol y a que movimiento artistico pertenece. Me apasiona conocer acerca del arte y sus exponentes.')
Question.create(name: '7. ', description: 'En general me intereso por las dificultades que ha tenido que atravesar la humanidad y como lo ha superado.')
Question.create(name: '8. ', description: 'Me apasiona leer y no me importa si el libro que elijo tiene muchas paginas, para mi es un gran entretenimiento.')
Question.create(name: '9. ', description: 'Me atrae conocer los procesos y las areas que hacen funcionar a las empresas.')
Question.create(name: '10. ', description: 'Me siento identificado con el pensamiento de algunos filosofos y escritores.')
Question.create(name: '11. ', description: 'Me encanta estudiar el cuerpo humano y conocer como funciona. Ademas, no me impresiona la sangre.')
Question.create(name: '12. ', description: 'Si pudiera elegir, pasaria mucho tiempo diseñando novedosos objetos o edificios en mi computadora.')
Question.create(name: '13. ', description: 'Si mi blog fuera tematico, trataria acerca de:')
Question.create(name: '14. ', description: 'Integraria un equipo de trabajo encargado de producir un audiovisual sobre:')
Question.create(name: '15. ', description: 'Seria importante destacarme como:')


#Create Choices
@questions = Question.all
Choice.create(text: 'si', question_id: @questions[0].id)
Choice.create(text: 'no', question_id: @questions[0].id)
Choice.create(text: 'si', question_id: @questions[1].id)
Choice.create(text: 'no', question_id: @questions[1].id)
Choice.create(text: 'si', question_id: @questions[2].id)
Choice.create(text: 'no', question_id: @questions[2].id)
Choice.create(text: 'si', question_id: @questions[3].id)
Choice.create(text: 'no', question_id: @questions[3].id)
Choice.create(text: 'si', question_id: @questions[4].id)
Choice.create(text: 'no', question_id: @questions[4].id)
Choice.create(text: 'si', question_id: @questions[5].id)
Choice.create(text: 'no', question_id: @questions[5].id)
Choice.create(text: 'si', question_id: @questions[6].id)
Choice.create(text: 'no', question_id: @questions[6].id)
Choice.create(text: 'si', question_id: @questions[7].id)
Choice.create(text: 'no', question_id: @questions[7].id)
Choice.create(text: 'si', question_id: @questions[8].id)
Choice.create(text: 'no', question_id: @questions[8].id)
Choice.create(text: 'si', question_id: @questions[9].id)
Choice.create(text: 'no', question_id: @questions[9].id)
Choice.create(text: 'si', question_id: @questions[10].id)
Choice.create(text: 'no', question_id: @questions[10].id)
Choice.create(text: 'si', question_id: @questions[11].id)
Choice.create(text: 'no', question_id: @questions[11].id)
Choice.create(text: 'La importancia de la expresion artistica en el desarrollo de la identidad de los pueblos.', question_id: @questions[12].id)
Choice.create(text: 'La arquelogia urbana como forma de aprender acerca de la historia cultural de una ciudad.', question_id: @questions[12].id)
Choice.create(text: 'La tecnologia satelital en un proyecto para descubrir actividad volcanica para prevenir catastrofes climaticas.', question_id: @questions[12].id)
Choice.create(text: 'Ninguna de las opciones.', question_id: @questions[12].id)
Choice.create(text: 'La practica de deportes y su influencia positiva en el estado de animo de las personas.', question_id: @questions[13].id)
Choice.create(text: 'Los pensadores del siglo XX y su aporte a la gestion de las organizaciones.', question_id: @questions[13].id)
Choice.create(text: 'Las mascotas y su incidencia en la calidad de vida de las personas no videntes.', question_id: @questions[13].id)
Choice.create(text: 'El uso de la PC como herramienta para el control de los procesos industriales.', question_id: @questions[13].id)
Choice.create(text: 'Procesos productivos de una empresa.', question_id: @questions[13].id)
Choice.create(text: 'Ninguna de las opciones.', question_id: @questions[13].id)
Choice.create(text: 'Director de una investigacion tecnico cientifica', question_id: @questions[14].id)
Choice.create(text: 'Gerente general de una empresa reconocida por su responsabilidad social.', question_id: @questions[14].id)
Choice.create(text: 'Un deportista famoso por su destreza fisica y su etica profesional.', question_id: @questions[14].id)
Choice.create(text: 'Experto en la deteccion precoz de enfermedades neurologicas en niños.', question_id: @questions[14].id)
Choice.create(text: 'Un agente de prensa audaz, numero uno en el ranking de notas a celebridades.', question_id: @questions[14].id)
Choice.create(text: 'Ninguna de las opciones.', question_id: @questions[14].id)


#Create Careers
Career.create(name: 'null', description: ' ') #This career object will be used to manage disconections or cancellations during the test
Career.create(name: 'Computacion', description: ' ')
Career.create(name: 'Veterinaria', description: ' ')
Career.create(name: 'Agronomia', description: ' ')
Career.create(name: 'Arquitectura', description: ' ')
Career.create(name: 'Arte', description: ' ')
Career.create(name: 'Economia', description: ' ')
Career.create(name: 'Educacion fisica', description: ' ')
Career.create(name: 'Filosofia', description: ' ')
Career.create(name: 'Fisica', description: ' ')
Career.create(name: 'Geologia', description: ' ')
Career.create(name: 'Historia', description: ' ')
Career.create(name: 'Literaruta', description: ' ')
Career.create(name: 'Matematicas', description: ' ')
Career.create(name: 'Medicina', description: ' ')
Career.create(name: 'Periodismo', description: ' ')
Career.create(name: 'Quimica', description: ' ')
Career.create(name: 'Sociologia', description: ' ')

#Create Outcomes
Outcome.create(choice_id: (Question.find(:name => '1. ').choices[0]).id, career_id: Career.find(:name => 'Veterinaria').id)
Outcome.create(choice_id: (Question.find(:name => '1. ').choices[0]).id, career_id: Career.find(:name => 'Agronomia').id)
Outcome.create(choice_id: (Question.find(:name => '2. ').choices[0]).id, career_id: Career.find(:name => 'Fisica').id)
Outcome.create(choice_id: (Question.find(:name => '2. ').choices[0]).id, career_id: Career.find(:name => 'Matematicas').id)
Outcome.create(choice_id: (Question.find(:name => '2. ').choices[0]).id, career_id: Career.find(:name => 'Quimica').id)
Outcome.create(choice_id: (Question.find(:name => '2. ').choices[0]).id, career_id: Career.find(:name => 'Computacion').id)
Outcome.create(choice_id: (Question.find(:name => '3. ').choices[0]).id, career_id: Career.find(:name => 'Literaruta').id)
Outcome.create(choice_id: (Question.find(:name => '3. ').choices[0]).id, career_id: Career.find(:name => 'Historia').id)
Outcome.create(choice_id: (Question.find(:name => '4. ').choices[0]).id, career_id: Career.find(:name => 'Fisica').id)
Outcome.create(choice_id: (Question.find(:name => '5. ').choices[0]).id, career_id: Career.find(:name => 'Computacion').id)
Outcome.create(choice_id: (Question.find(:name => '6. ').choices[0]).id, career_id: Career.find(:name => 'Arte').id)
Outcome.create(choice_id: (Question.find(:name => '7. ').choices[0]).id, career_id: Career.find(:name => 'Historia').id)
Outcome.create(choice_id: (Question.find(:name => '8. ').choices[0]).id, career_id: Career.find(:name => 'Literaruta').id)
Outcome.create(choice_id: (Question.find(:name => '8. ').choices[0]).id, career_id: Career.find(:name => 'Historia').id)
Outcome.create(choice_id: (Question.find(:name => '9. ').choices[0]).id, career_id: Career.find(:name => 'Economia').id)
Outcome.create(choice_id: (Question.find(:name => '10. ').choices[0]).id, career_id: Career.find(:name => 'Filosofia').id)
Outcome.create(choice_id: (Question.find(:name => '10. ').choices[0]).id, career_id: Career.find(:name => 'Historia').id)
Outcome.create(choice_id: (Question.find(:name => '11. ').choices[0]).id, career_id: Career.find(:name => 'Medicina').id)
Outcome.create(choice_id: (Question.find(:name => '12. ').choices[0]).id, career_id: Career.find(:name => 'Computacion').id)
Outcome.create(choice_id: (Question.find(:name => '12. ').choices[0]).id, career_id: Career.find(:name => 'Arquitectura').id)
Outcome.create(choice_id: (Question.find(:name => '13. ').choices[0]).id, career_id: Career.find(:name => 'Sociologia').id)
Outcome.create(choice_id: (Question.find(:name => '13. ').choices[1]).id, career_id: Career.find(:name => 'Historia').id)
Outcome.create(choice_id: (Question.find(:name => '13. ').choices[2]).id, career_id: Career.find(:name => 'Computacion').id)
Outcome.create(choice_id: (Question.find(:name => '13. ').choices[2]).id, career_id: Career.find(:name => 'Geologia').id)
Outcome.create(choice_id: (Question.find(:name => '14. ').choices[0]).id, career_id: Career.find(:name => 'Educacion fisica').id)
Outcome.create(choice_id: (Question.find(:name => '14. ').choices[1]).id, career_id: Career.find(:name => 'Filosofia').id)
Outcome.create(choice_id: (Question.find(:name => '14. ').choices[1]).id, career_id: Career.find(:name => 'Historia').id)
Outcome.create(choice_id: (Question.find(:name => '14. ').choices[2]).id, career_id: Career.find(:name => 'Veterinaria').id)
Outcome.create(choice_id: (Question.find(:name => '14. ').choices[3]).id, career_id: Career.find(:name => 'Computacion').id)
Outcome.create(choice_id: (Question.find(:name => '14. ').choices[4]).id, career_id: Career.find(:name => 'Economia').id)
Outcome.create(choice_id: (Question.find(:name => '15. ').choices[0]).id, career_id: Career.find(:name => 'Fisica').id)
Outcome.create(choice_id: (Question.find(:name => '15. ').choices[0]).id, career_id: Career.find(:name => 'Quimica').id)
Outcome.create(choice_id: (Question.find(:name => '15. ').choices[0]).id, career_id: Career.find(:name => 'Computacion').id)
Outcome.create(choice_id: (Question.find(:name => '15. ').choices[1]).id, career_id: Career.find(:name => 'Economia').id)
Outcome.create(choice_id: (Question.find(:name => '15. ').choices[2]).id, career_id: Career.find(:name => 'Educacion fisica').id)
Outcome.create(choice_id: (Question.find(:name => '15. ').choices[3]).id, career_id: Career.find(:name => 'Medicina').id)
Outcome.create(choice_id: (Question.find(:name => '15. ').choices[4]).id, career_id: Career.find(:name => 'Periodismo').id)
